/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrecoFinalCarro;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        
        
        /*O custo de um carro novo ao consumidoré a soma do custo de fábrica mais o percentual do distribuidor e 
dos impostos aplicados (primeiro os impostos são aplicados sobre o custo de fábrica, e depois o percentual 
do distribuidor sobre o resultado). Supondo que o percentual do distribuidor seja de 28% e os impostos 
45%, escreva um algoritmo que leia o custo de fábrica de um carro e informe o custo ao consumidor do 
mesmo;*/
        
        float custoFabrica = 0;
        float percentualDistribuidor = 0.28f;
        float impostos = 0.45f;
        float resultado = 0;
        float precoFinal = 0;
        
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Qual o custo do fabricante: R$ ");
        custoFabrica = leitor.nextFloat();
        
        System.out.println("Percentual do distribuidor: " + percentualDistribuidor);
        System.out.println("Impostos: R$ " + impostos);
        
        resultado = (custoFabrica * impostos)+ custoFabrica;
        precoFinal = (resultado * percentualDistribuidor) + resultado;
        
        System.out.println("Preco final de venda: R$ " + precoFinal);
        
        
        
        
        
        
        
        
        
    }
}
